#!/bin/sh
set -e

if ! getent group nihility >/dev/null; then
    addgroup --system nihility
fi

install -d -o root -g nihility -m 0750 /etc/nsetup
install -d -o root -g nihility -m 0750 /var/lib/nsetup
install -d -o root -g nihility -m 0750 /var/lib/nsetup/stacks
install -d -o root -g nihility -m 0750 /var/lib/nsetup/data
chown root:nihility /etc/nsetup/config.toml
chmod 0640 /etc/nsetup/config.toml

systemctl daemon-reload >/dev/null 2>&1 || true
systemctl enable nsetup.service >/dev/null 2>&1 || true
systemctl restart nsetup.service >/dev/null 2>&1 || true

exit 0
